
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `gtsummary`=list(
        `type`="article", 
        `author`="Sjoberg, D. D., Whiting, K., Curry, M., Lavery, J. A., & Larmarange, J.", 
        `year`=2021, 
        `title`="Reproducible Summary Tables with the gtsummary Package", 
        `publisher`="The R Journal", 
        `volume`=13, 
        `issue`=1, 
        `pages`="570-580", 
        `url`="https://doi.org/10.32614/RJ-2021-053"))
