
# This file is automatically generated, you probably don't want to edit this

tblContinuousOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblContinuousOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            contVar = NULL,
            varsCat = NULL,
            groupVar = NULL,
            addOverall = FALSE,
            addOverallLast = FALSE,
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            sortCatDefault = "default",
            sortCatSpecific = NULL,
            statDefault = "meanSd",
            statSpecific = NULL,
            digitsCont = "auto",
            addPvalue = FALSE,
            testDefault = "parametric",
            testSpecific = NULL,
            digitsPvalue = "auto",
            boldPvalue = FALSE,
            boldPvalueThreshold = 0.05,
            addQ = FALSE,
            qMethod = "BH",
            boldQ = FALSE,
            boldQThreshold = 0.05, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblContinuous",
                requiresData=TRUE,
                ...)

            private$..contVar <- jmvcore::OptionVariable$new(
                "contVar",
                contVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..varsCat <- jmvcore::OptionVariables$new(
                "varsCat",
                varsCat,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..addOverall <- jmvcore::OptionBool$new(
                "addOverall",
                addOverall,
                default=FALSE)
            private$..addOverallLast <- jmvcore::OptionBool$new(
                "addOverallLast",
                addOverallLast,
                default=FALSE)
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..sortCatDefault <- jmvcore::OptionList$new(
                "sortCatDefault",
                sortCatDefault,
                options=list(
                    "default",
                    "frequency"),
                default="default")
            private$..sortCatSpecific <- jmvcore::OptionArray$new(
                "sortCatSpecific",
                sortCatSpecific,
                template=jmvcore::OptionGroup$new(
                    "sortCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "sort",
                            NULL,
                            options=list(
                                "useDefault",
                                "default",
                                "frequency"),
                            default="useDefault"))))
            private$..statDefault <- jmvcore::OptionList$new(
                "statDefault",
                statDefault,
                options=list(
                    "meanSd",
                    "medianIqr",
                    "medianRange",
                    "mean",
                    "median"),
                default="meanSd")
            private$..statSpecific <- jmvcore::OptionArray$new(
                "statSpecific",
                statSpecific,
                template=jmvcore::OptionGroup$new(
                    "statSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "useDefault",
                                "meanSd",
                                "medianIqr",
                                "medianRange",
                                "mean",
                                "median"),
                            default="useDefault"))))
            private$..digitsCont <- jmvcore::OptionList$new(
                "digitsCont",
                digitsCont,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..addPvalue <- jmvcore::OptionBool$new(
                "addPvalue",
                addPvalue,
                default=FALSE)
            private$..testDefault <- jmvcore::OptionList$new(
                "testDefault",
                testDefault,
                options=list(
                    "parametric",
                    "nonparametric",
                    "t.test",
                    "t.test.equalVar",
                    "oneway.test",
                    "oneway.test.equalVar",
                    "wilcox.test",
                    "kruskal.test"),
                default="parametric")
            private$..testSpecific <- jmvcore::OptionArray$new(
                "testSpecific",
                testSpecific,
                template=jmvcore::OptionGroup$new(
                    "testSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "test",
                            NULL,
                            options=list(
                                "useDefault",
                                "t.test",
                                "t.test.equalVar",
                                "oneway.test",
                                "oneway.test.equalVar",
                                "wilcox.test",
                                "kruskal.test"),
                            default="useDefault"))))
            private$..digitsPvalue <- jmvcore::OptionList$new(
                "digitsPvalue",
                digitsPvalue,
                options=list(
                    "auto",
                    "1",
                    "2",
                    "3"),
                default="auto")
            private$..boldPvalue <- jmvcore::OptionBool$new(
                "boldPvalue",
                boldPvalue,
                default=FALSE)
            private$..boldPvalueThreshold <- jmvcore::OptionNumber$new(
                "boldPvalueThreshold",
                boldPvalueThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..addQ <- jmvcore::OptionBool$new(
                "addQ",
                addQ,
                default=FALSE)
            private$..qMethod <- jmvcore::OptionList$new(
                "qMethod",
                qMethod,
                options=list(
                    "BH",
                    "BY",
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "none"),
                default="BH")
            private$..boldQ <- jmvcore::OptionBool$new(
                "boldQ",
                boldQ,
                default=FALSE)
            private$..boldQThreshold <- jmvcore::OptionNumber$new(
                "boldQThreshold",
                boldQThreshold,
                min=0,
                max=1,
                default=0.05)

            self$.addOption(private$..contVar)
            self$.addOption(private$..varsCat)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..addOverall)
            self$.addOption(private$..addOverallLast)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..sortCatDefault)
            self$.addOption(private$..sortCatSpecific)
            self$.addOption(private$..statDefault)
            self$.addOption(private$..statSpecific)
            self$.addOption(private$..digitsCont)
            self$.addOption(private$..addPvalue)
            self$.addOption(private$..testDefault)
            self$.addOption(private$..testSpecific)
            self$.addOption(private$..digitsPvalue)
            self$.addOption(private$..boldPvalue)
            self$.addOption(private$..boldPvalueThreshold)
            self$.addOption(private$..addQ)
            self$.addOption(private$..qMethod)
            self$.addOption(private$..boldQ)
            self$.addOption(private$..boldQThreshold)
        }),
    active = list(
        contVar = function() private$..contVar$value,
        varsCat = function() private$..varsCat$value,
        groupVar = function() private$..groupVar$value,
        addOverall = function() private$..addOverall$value,
        addOverallLast = function() private$..addOverallLast$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        sortCatDefault = function() private$..sortCatDefault$value,
        sortCatSpecific = function() private$..sortCatSpecific$value,
        statDefault = function() private$..statDefault$value,
        statSpecific = function() private$..statSpecific$value,
        digitsCont = function() private$..digitsCont$value,
        addPvalue = function() private$..addPvalue$value,
        testDefault = function() private$..testDefault$value,
        testSpecific = function() private$..testSpecific$value,
        digitsPvalue = function() private$..digitsPvalue$value,
        boldPvalue = function() private$..boldPvalue$value,
        boldPvalueThreshold = function() private$..boldPvalueThreshold$value,
        addQ = function() private$..addQ$value,
        qMethod = function() private$..qMethod$value,
        boldQ = function() private$..boldQ$value,
        boldQThreshold = function() private$..boldQThreshold$value),
    private = list(
        ..contVar = NA,
        ..varsCat = NA,
        ..groupVar = NA,
        ..addOverall = NA,
        ..addOverallLast = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..sortCatDefault = NA,
        ..sortCatSpecific = NA,
        ..statDefault = NA,
        ..statSpecific = NA,
        ..digitsCont = NA,
        ..addPvalue = NA,
        ..testDefault = NA,
        ..testSpecific = NA,
        ..digitsPvalue = NA,
        ..boldPvalue = NA,
        ..boldPvalueThreshold = NA,
        ..addQ = NA,
        ..qMethod = NA,
        ..boldQ = NA,
        ..boldQThreshold = NA)
)

tblContinuousResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblContinuousResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Table")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblContinuousBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblContinuousBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblContinuous",
                version = c(1,0,0),
                options = options,
                results = tblContinuousResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Continuous Table
#'
#' 
#' @param data .
#' @param contVar .
#' @param varsCat .
#' @param groupVar .
#' @param addOverall .
#' @param addOverallLast .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param sortCatDefault .
#' @param sortCatSpecific .
#' @param statDefault .
#' @param statSpecific .
#' @param digitsCont .
#' @param addPvalue .
#' @param testDefault .
#' @param testSpecific .
#' @param digitsPvalue .
#' @param boldPvalue .
#' @param boldPvalueThreshold .
#' @param addQ .
#' @param qMethod .
#' @param boldQ .
#' @param boldQThreshold .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblContinuous <- function(
    data,
    contVar,
    varsCat,
    groupVar,
    addOverall = FALSE,
    addOverallLast = FALSE,
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    sortCatDefault = "default",
    sortCatSpecific,
    statDefault = "meanSd",
    statSpecific,
    digitsCont = "auto",
    addPvalue = FALSE,
    testDefault = "parametric",
    testSpecific,
    digitsPvalue = "auto",
    boldPvalue = FALSE,
    boldPvalueThreshold = 0.05,
    addQ = FALSE,
    qMethod = "BH",
    boldQ = FALSE,
    boldQThreshold = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblContinuous requires jmvcore to be installed (restart may be required)")

    if ( ! missing(contVar)) contVar <- jmvcore::resolveQuo(jmvcore::enquo(contVar))
    if ( ! missing(varsCat)) varsCat <- jmvcore::resolveQuo(jmvcore::enquo(varsCat))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(contVar), contVar, NULL),
            `if`( ! missing(varsCat), varsCat, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))

    for (v in varsCat) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in groupVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- tblContinuousOptions$new(
        contVar = contVar,
        varsCat = varsCat,
        groupVar = groupVar,
        addOverall = addOverall,
        addOverallLast = addOverallLast,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        sortCatDefault = sortCatDefault,
        sortCatSpecific = sortCatSpecific,
        statDefault = statDefault,
        statSpecific = statSpecific,
        digitsCont = digitsCont,
        addPvalue = addPvalue,
        testDefault = testDefault,
        testSpecific = testSpecific,
        digitsPvalue = digitsPvalue,
        boldPvalue = boldPvalue,
        boldPvalueThreshold = boldPvalueThreshold,
        addQ = addQ,
        qMethod = qMethod,
        boldQ = boldQ,
        boldQThreshold = boldQThreshold)

    analysis <- tblContinuousClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

