
# This file is automatically generated, you probably don't want to edit this

tblCrossOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblCrossOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            row = NULL,
            col = NULL,
            statistic = "nPercent",
            percent = "column",
            digits = "auto",
            margin = "both",
            marginText = "Total",
            missing = "ifany",
            missingText = "Unknown",
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            addPvalue = FALSE,
            testDefault = "auto",
            digitsPvalue = "auto",
            boldPvalue = FALSE,
            boldPvalueThreshold = 0.05,
            sourceNote = FALSE, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblCross",
                requiresData=TRUE,
                ...)

            private$..row <- jmvcore::OptionVariable$new(
                "row",
                row,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..col <- jmvcore::OptionVariable$new(
                "col",
                col,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..statistic <- jmvcore::OptionList$new(
                "statistic",
                statistic,
                options=list(
                    "nPercent",
                    "n",
                    "percent"),
                default="nPercent")
            private$..percent <- jmvcore::OptionList$new(
                "percent",
                percent,
                options=list(
                    "column",
                    "row",
                    "cell"),
                default="column")
            private$..digits <- jmvcore::OptionList$new(
                "digits",
                digits,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..margin <- jmvcore::OptionList$new(
                "margin",
                margin,
                options=list(
                    "both",
                    "row",
                    "column",
                    "none"),
                default="both")
            private$..marginText <- jmvcore::OptionString$new(
                "marginText",
                marginText,
                default="Total")
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "ifany",
                    "no",
                    "always"),
                default="ifany")
            private$..missingText <- jmvcore::OptionString$new(
                "missingText",
                missingText,
                default="Unknown")
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..addPvalue <- jmvcore::OptionBool$new(
                "addPvalue",
                addPvalue,
                default=FALSE)
            private$..testDefault <- jmvcore::OptionList$new(
                "testDefault",
                testDefault,
                options=list(
                    "auto",
                    "chisq.test.no.correct",
                    "chisq.test",
                    "fisher.test"),
                default="auto")
            private$..digitsPvalue <- jmvcore::OptionList$new(
                "digitsPvalue",
                digitsPvalue,
                options=list(
                    "auto",
                    "1",
                    "2",
                    "3"),
                default="auto")
            private$..boldPvalue <- jmvcore::OptionBool$new(
                "boldPvalue",
                boldPvalue,
                default=FALSE)
            private$..boldPvalueThreshold <- jmvcore::OptionNumber$new(
                "boldPvalueThreshold",
                boldPvalueThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..sourceNote <- jmvcore::OptionBool$new(
                "sourceNote",
                sourceNote,
                default=FALSE)

            self$.addOption(private$..row)
            self$.addOption(private$..col)
            self$.addOption(private$..statistic)
            self$.addOption(private$..percent)
            self$.addOption(private$..digits)
            self$.addOption(private$..margin)
            self$.addOption(private$..marginText)
            self$.addOption(private$..missing)
            self$.addOption(private$..missingText)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..addPvalue)
            self$.addOption(private$..testDefault)
            self$.addOption(private$..digitsPvalue)
            self$.addOption(private$..boldPvalue)
            self$.addOption(private$..boldPvalueThreshold)
            self$.addOption(private$..sourceNote)
        }),
    active = list(
        row = function() private$..row$value,
        col = function() private$..col$value,
        statistic = function() private$..statistic$value,
        percent = function() private$..percent$value,
        digits = function() private$..digits$value,
        margin = function() private$..margin$value,
        marginText = function() private$..marginText$value,
        missing = function() private$..missing$value,
        missingText = function() private$..missingText$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        addPvalue = function() private$..addPvalue$value,
        testDefault = function() private$..testDefault$value,
        digitsPvalue = function() private$..digitsPvalue$value,
        boldPvalue = function() private$..boldPvalue$value,
        boldPvalueThreshold = function() private$..boldPvalueThreshold$value,
        sourceNote = function() private$..sourceNote$value),
    private = list(
        ..row = NA,
        ..col = NA,
        ..statistic = NA,
        ..percent = NA,
        ..digits = NA,
        ..margin = NA,
        ..marginText = NA,
        ..missing = NA,
        ..missingText = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..addPvalue = NA,
        ..testDefault = NA,
        ..digitsPvalue = NA,
        ..boldPvalue = NA,
        ..boldPvalueThreshold = NA,
        ..sourceNote = NA)
)

tblCrossResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblCrossResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Cross Table")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblCrossBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblCrossBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblCross",
                version = c(1,0,0),
                options = options,
                results = tblCrossResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Cross Table
#'
#' 
#' @param data .
#' @param row .
#' @param col .
#' @param statistic .
#' @param percent .
#' @param digits .
#' @param margin .
#' @param marginText .
#' @param missing .
#' @param missingText .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param addPvalue .
#' @param testDefault .
#' @param digitsPvalue .
#' @param boldPvalue .
#' @param boldPvalueThreshold .
#' @param sourceNote .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblCross <- function(
    data,
    row,
    col,
    statistic = "nPercent",
    percent = "column",
    digits = "auto",
    margin = "both",
    marginText = "Total",
    missing = "ifany",
    missingText = "Unknown",
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    addPvalue = FALSE,
    testDefault = "auto",
    digitsPvalue = "auto",
    boldPvalue = FALSE,
    boldPvalueThreshold = 0.05,
    sourceNote = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblCross requires jmvcore to be installed (restart may be required)")

    if ( ! missing(row)) row <- jmvcore::resolveQuo(jmvcore::enquo(row))
    if ( ! missing(col)) col <- jmvcore::resolveQuo(jmvcore::enquo(col))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(row), row, NULL),
            `if`( ! missing(col), col, NULL))

    for (v in row) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in col) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- tblCrossOptions$new(
        row = row,
        col = col,
        statistic = statistic,
        percent = percent,
        digits = digits,
        margin = margin,
        marginText = marginText,
        missing = missing,
        missingText = missingText,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        addPvalue = addPvalue,
        testDefault = testDefault,
        digitsPvalue = digitsPvalue,
        boldPvalue = boldPvalue,
        boldPvalueThreshold = boldPvalueThreshold,
        sourceNote = sourceNote)

    analysis <- tblCrossClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

