
# This file is automatically generated, you probably don't want to edit this

tblLikertOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblLikertOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            statistic = "nPercent",
            statSpecific = NULL,
            digits = "auto",
            levelOrder = "asFirst",
            addN = FALSE,
            addNLast = FALSE,
            addNFootnote = TRUE,
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            italicizeLabels = FALSE,
            path = "~/Desktop/Likert Table.docx",
            export = FALSE, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblLikert",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..statistic <- jmvcore::OptionList$new(
                "statistic",
                statistic,
                options=list(
                    "nPercent",
                    "n",
                    "percent"),
                default="nPercent")
            private$..statSpecific <- jmvcore::OptionArray$new(
                "statSpecific",
                statSpecific,
                template=jmvcore::OptionGroup$new(
                    "statSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "useDefault",
                                "nPercent",
                                "n",
                                "percent"),
                            default="useDefault"))))
            private$..digits <- jmvcore::OptionList$new(
                "digits",
                digits,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..levelOrder <- jmvcore::OptionList$new(
                "levelOrder",
                levelOrder,
                options=list(
                    "asFirst",
                    "reversed"),
                default="asFirst")
            private$..addN <- jmvcore::OptionBool$new(
                "addN",
                addN,
                default=FALSE)
            private$..addNLast <- jmvcore::OptionBool$new(
                "addNLast",
                addNLast,
                default=FALSE)
            private$..addNFootnote <- jmvcore::OptionBool$new(
                "addNFootnote",
                addNFootnote,
                default=TRUE)
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/Likert Table.docx")
            private$..export <- jmvcore::OptionAction$new(
                "export",
                export)

            self$.addOption(private$..vars)
            self$.addOption(private$..statistic)
            self$.addOption(private$..statSpecific)
            self$.addOption(private$..digits)
            self$.addOption(private$..levelOrder)
            self$.addOption(private$..addN)
            self$.addOption(private$..addNLast)
            self$.addOption(private$..addNFootnote)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..path)
            self$.addOption(private$..export)
        }),
    active = list(
        vars = function() private$..vars$value,
        statistic = function() private$..statistic$value,
        statSpecific = function() private$..statSpecific$value,
        digits = function() private$..digits$value,
        levelOrder = function() private$..levelOrder$value,
        addN = function() private$..addN$value,
        addNLast = function() private$..addNLast$value,
        addNFootnote = function() private$..addNFootnote$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        path = function() private$..path$value,
        export = function() private$..export$value),
    private = list(
        ..vars = NA,
        ..statistic = NA,
        ..statSpecific = NA,
        ..digits = NA,
        ..levelOrder = NA,
        ..addN = NA,
        ..addNLast = NA,
        ..addNFootnote = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..italicizeLabels = NA,
        ..path = NA,
        ..export = NA)
)

tblLikertResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblLikertResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Likert Table")
            self$add(jmvcore::Table$new(
                options=options,
                name="status",
                title="Generating Table\u2026",
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblLikertBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblLikertBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblLikert",
                version = c(1,0,0),
                options = options,
                results = tblLikertResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Likert Table
#'
#' 
#' @param data .
#' @param vars .
#' @param statistic .
#' @param statSpecific .
#' @param digits .
#' @param levelOrder .
#' @param addN .
#' @param addNLast .
#' @param addNFootnote .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param italicizeLabels .
#' @param path .
#' @param export .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$status$asDF}
#'
#' \code{as.data.frame(results$status)}
#'
#' @export
tblLikert <- function(
    data,
    vars,
    statistic = "nPercent",
    statSpecific,
    digits = "auto",
    levelOrder = "asFirst",
    addN = FALSE,
    addNLast = FALSE,
    addNFootnote = TRUE,
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    italicizeLabels = FALSE,
    path = "~/Desktop/Likert Table.docx",
    export = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblLikert requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- tblLikertOptions$new(
        vars = vars,
        statistic = statistic,
        statSpecific = statSpecific,
        digits = digits,
        levelOrder = levelOrder,
        addN = addN,
        addNLast = addNLast,
        addNFootnote = addNFootnote,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        italicizeLabels = italicizeLabels,
        path = path,
        export = export)

    analysis <- tblLikertClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

