
# This file is automatically generated, you probably don't want to edit this

tblRegLinearOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLinearOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            modelTerms = NULL,
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            addQ = FALSE,
            qMethod = "BH",
            boldQ = FALSE,
            boldQThreshold = 0.05,
            path = "~/Desktop/Linear Regression Table.docx",
            export = FALSE, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblRegLinear",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms)
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..addQ <- jmvcore::OptionBool$new(
                "addQ",
                addQ,
                default=FALSE)
            private$..qMethod <- jmvcore::OptionList$new(
                "qMethod",
                qMethod,
                options=list(
                    "BH",
                    "BY",
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "none"),
                default="BH")
            private$..boldQ <- jmvcore::OptionBool$new(
                "boldQ",
                boldQ,
                default=FALSE)
            private$..boldQThreshold <- jmvcore::OptionNumber$new(
                "boldQThreshold",
                boldQThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/Linear Regression Table.docx")
            private$..export <- jmvcore::OptionAction$new(
                "export",
                export)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..addQ)
            self$.addOption(private$..qMethod)
            self$.addOption(private$..boldQ)
            self$.addOption(private$..boldQThreshold)
            self$.addOption(private$..path)
            self$.addOption(private$..export)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        modelTerms = function() private$..modelTerms$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        addQ = function() private$..addQ$value,
        qMethod = function() private$..qMethod$value,
        boldQ = function() private$..boldQ$value,
        boldQThreshold = function() private$..boldQThreshold$value,
        path = function() private$..path$value,
        export = function() private$..export$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..modelTerms = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..addQ = NA,
        ..qMethod = NA,
        ..boldQ = NA,
        ..boldQThreshold = NA,
        ..path = NA,
        ..export = NA)
)

tblRegLinearResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLinearResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariable Linear Regression")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblRegLinearBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLinearBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblRegLinear",
                version = c(1,0,0),
                options = options,
                results = tblRegLinearResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multivariable Linear Regression
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param modelTerms .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param addQ .
#' @param qMethod .
#' @param boldQ .
#' @param boldQThreshold .
#' @param path .
#' @param export .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblRegLinear <- function(
    data,
    dep,
    covs,
    factors,
    modelTerms,
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    addQ = FALSE,
    qMethod = "BH",
    boldQ = FALSE,
    boldQThreshold = 0.05,
    path = "~/Desktop/Linear Regression Table.docx",
    export = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblRegLinear requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(modelTerms, "formula")) modelTerms <- jmvcore::decomposeFormula(modelTerms)

    options <- tblRegLinearOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        modelTerms = modelTerms,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        addQ = addQ,
        qMethod = qMethod,
        boldQ = boldQ,
        boldQThreshold = boldQThreshold,
        path = path,
        export = export)

    analysis <- tblRegLinearClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

