
# This file is automatically generated, you probably don't want to edit this

tblRegLogisticOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLogisticOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL,
            factors = NULL,
            modelTerms = NULL,
            exponentiate = TRUE,
            digitsCoef = "auto",
            confInt = TRUE,
            confLevel = 95,
            ciMerge = FALSE,
            intercept = FALSE,
            addRefRowEstimate = FALSE,
            addN = FALSE,
            addNLocation = "label",
            addNEvent = FALSE,
            addNEventLocation = "label",
            addVif = FALSE,
            modelFit = "none",
            digitsPvalue = "auto",
            boldPvalue = FALSE,
            boldPvalueThreshold = 0.05,
            globalP = FALSE,
            globalPKeep = FALSE,
            addStars = FALSE,
            starsShowCi = FALSE,
            starsShowP = FALSE,
            starsShowSe = TRUE,
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            addQ = FALSE,
            qMethod = "BH",
            boldQ = FALSE,
            boldQThreshold = 0.05,
            path = "~/Desktop/Multivariable Logistic Regression.docx",
            export = FALSE, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblRegLogistic",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                rejectUnusedLevels=TRUE,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms)
            private$..exponentiate <- jmvcore::OptionBool$new(
                "exponentiate",
                exponentiate,
                default=TRUE)
            private$..digitsCoef <- jmvcore::OptionList$new(
                "digitsCoef",
                digitsCoef,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..confInt <- jmvcore::OptionBool$new(
                "confInt",
                confInt,
                default=TRUE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=50,
                max=99.9,
                default=95)
            private$..ciMerge <- jmvcore::OptionBool$new(
                "ciMerge",
                ciMerge,
                default=FALSE)
            private$..intercept <- jmvcore::OptionBool$new(
                "intercept",
                intercept,
                default=FALSE)
            private$..addRefRowEstimate <- jmvcore::OptionBool$new(
                "addRefRowEstimate",
                addRefRowEstimate,
                default=FALSE)
            private$..addN <- jmvcore::OptionBool$new(
                "addN",
                addN,
                default=FALSE)
            private$..addNLocation <- jmvcore::OptionList$new(
                "addNLocation",
                addNLocation,
                options=list(
                    "label",
                    "level",
                    "both"),
                default="label")
            private$..addNEvent <- jmvcore::OptionBool$new(
                "addNEvent",
                addNEvent,
                default=FALSE)
            private$..addNEventLocation <- jmvcore::OptionList$new(
                "addNEventLocation",
                addNEventLocation,
                options=list(
                    "label",
                    "level",
                    "both"),
                default="label")
            private$..addVif <- jmvcore::OptionBool$new(
                "addVif",
                addVif,
                default=FALSE)
            private$..modelFit <- jmvcore::OptionList$new(
                "modelFit",
                modelFit,
                options=list(
                    "none",
                    "footnote",
                    "table"),
                default="none")
            private$..digitsPvalue <- jmvcore::OptionList$new(
                "digitsPvalue",
                digitsPvalue,
                options=list(
                    "auto",
                    "1",
                    "2",
                    "3"),
                default="auto")
            private$..boldPvalue <- jmvcore::OptionBool$new(
                "boldPvalue",
                boldPvalue,
                default=FALSE)
            private$..boldPvalueThreshold <- jmvcore::OptionNumber$new(
                "boldPvalueThreshold",
                boldPvalueThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..globalP <- jmvcore::OptionBool$new(
                "globalP",
                globalP,
                default=FALSE)
            private$..globalPKeep <- jmvcore::OptionBool$new(
                "globalPKeep",
                globalPKeep,
                default=FALSE)
            private$..addStars <- jmvcore::OptionBool$new(
                "addStars",
                addStars,
                default=FALSE)
            private$..starsShowCi <- jmvcore::OptionBool$new(
                "starsShowCi",
                starsShowCi,
                default=FALSE)
            private$..starsShowP <- jmvcore::OptionBool$new(
                "starsShowP",
                starsShowP,
                default=FALSE)
            private$..starsShowSe <- jmvcore::OptionBool$new(
                "starsShowSe",
                starsShowSe,
                default=TRUE)
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..addQ <- jmvcore::OptionBool$new(
                "addQ",
                addQ,
                default=FALSE)
            private$..qMethod <- jmvcore::OptionList$new(
                "qMethod",
                qMethod,
                options=list(
                    "BH",
                    "BY",
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "none"),
                default="BH")
            private$..boldQ <- jmvcore::OptionBool$new(
                "boldQ",
                boldQ,
                default=FALSE)
            private$..boldQThreshold <- jmvcore::OptionNumber$new(
                "boldQThreshold",
                boldQThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/Multivariable Logistic Regression.docx")
            private$..export <- jmvcore::OptionAction$new(
                "export",
                export)

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
            self$.addOption(private$..factors)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..exponentiate)
            self$.addOption(private$..digitsCoef)
            self$.addOption(private$..confInt)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..ciMerge)
            self$.addOption(private$..intercept)
            self$.addOption(private$..addRefRowEstimate)
            self$.addOption(private$..addN)
            self$.addOption(private$..addNLocation)
            self$.addOption(private$..addNEvent)
            self$.addOption(private$..addNEventLocation)
            self$.addOption(private$..addVif)
            self$.addOption(private$..modelFit)
            self$.addOption(private$..digitsPvalue)
            self$.addOption(private$..boldPvalue)
            self$.addOption(private$..boldPvalueThreshold)
            self$.addOption(private$..globalP)
            self$.addOption(private$..globalPKeep)
            self$.addOption(private$..addStars)
            self$.addOption(private$..starsShowCi)
            self$.addOption(private$..starsShowP)
            self$.addOption(private$..starsShowSe)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..addQ)
            self$.addOption(private$..qMethod)
            self$.addOption(private$..boldQ)
            self$.addOption(private$..boldQThreshold)
            self$.addOption(private$..path)
            self$.addOption(private$..export)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value,
        factors = function() private$..factors$value,
        modelTerms = function() private$..modelTerms$value,
        exponentiate = function() private$..exponentiate$value,
        digitsCoef = function() private$..digitsCoef$value,
        confInt = function() private$..confInt$value,
        confLevel = function() private$..confLevel$value,
        ciMerge = function() private$..ciMerge$value,
        intercept = function() private$..intercept$value,
        addRefRowEstimate = function() private$..addRefRowEstimate$value,
        addN = function() private$..addN$value,
        addNLocation = function() private$..addNLocation$value,
        addNEvent = function() private$..addNEvent$value,
        addNEventLocation = function() private$..addNEventLocation$value,
        addVif = function() private$..addVif$value,
        modelFit = function() private$..modelFit$value,
        digitsPvalue = function() private$..digitsPvalue$value,
        boldPvalue = function() private$..boldPvalue$value,
        boldPvalueThreshold = function() private$..boldPvalueThreshold$value,
        globalP = function() private$..globalP$value,
        globalPKeep = function() private$..globalPKeep$value,
        addStars = function() private$..addStars$value,
        starsShowCi = function() private$..starsShowCi$value,
        starsShowP = function() private$..starsShowP$value,
        starsShowSe = function() private$..starsShowSe$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        addQ = function() private$..addQ$value,
        qMethod = function() private$..qMethod$value,
        boldQ = function() private$..boldQ$value,
        boldQThreshold = function() private$..boldQThreshold$value,
        path = function() private$..path$value,
        export = function() private$..export$value),
    private = list(
        ..dep = NA,
        ..covs = NA,
        ..factors = NA,
        ..modelTerms = NA,
        ..exponentiate = NA,
        ..digitsCoef = NA,
        ..confInt = NA,
        ..confLevel = NA,
        ..ciMerge = NA,
        ..intercept = NA,
        ..addRefRowEstimate = NA,
        ..addN = NA,
        ..addNLocation = NA,
        ..addNEvent = NA,
        ..addNEventLocation = NA,
        ..addVif = NA,
        ..modelFit = NA,
        ..digitsPvalue = NA,
        ..boldPvalue = NA,
        ..boldPvalueThreshold = NA,
        ..globalP = NA,
        ..globalPKeep = NA,
        ..addStars = NA,
        ..starsShowCi = NA,
        ..starsShowP = NA,
        ..starsShowSe = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..addQ = NA,
        ..qMethod = NA,
        ..boldQ = NA,
        ..boldQThreshold = NA,
        ..path = NA,
        ..export = NA)
)

tblRegLogisticResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLogisticResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multivariable Logistic Regression")
            self$add(jmvcore::Table$new(
                options=options,
                name="status",
                title="Generating Table\u2026",
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblRegLogisticBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblRegLogisticBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblRegLogistic",
                version = c(1,0,0),
                options = options,
                results = tblRegLogisticResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Multivariable Logistic Regression
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @param factors .
#' @param modelTerms .
#' @param exponentiate .
#' @param digitsCoef .
#' @param confInt .
#' @param confLevel .
#' @param ciMerge .
#' @param intercept .
#' @param addRefRowEstimate .
#' @param addN .
#' @param addNLocation .
#' @param addNEvent .
#' @param addNEventLocation .
#' @param addVif .
#' @param modelFit .
#' @param digitsPvalue .
#' @param boldPvalue .
#' @param boldPvalueThreshold .
#' @param globalP .
#' @param globalPKeep .
#' @param addStars .
#' @param starsShowCi .
#' @param starsShowP .
#' @param starsShowSe .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param addQ .
#' @param qMethod .
#' @param boldQ .
#' @param boldQThreshold .
#' @param path .
#' @param export .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$status$asDF}
#'
#' \code{as.data.frame(results$status)}
#'
#' @export
tblRegLogistic <- function(
    data,
    dep,
    covs,
    factors,
    modelTerms,
    exponentiate = TRUE,
    digitsCoef = "auto",
    confInt = TRUE,
    confLevel = 95,
    ciMerge = FALSE,
    intercept = FALSE,
    addRefRowEstimate = FALSE,
    addN = FALSE,
    addNLocation = "label",
    addNEvent = FALSE,
    addNEventLocation = "label",
    addVif = FALSE,
    modelFit = "none",
    digitsPvalue = "auto",
    boldPvalue = FALSE,
    boldPvalueThreshold = 0.05,
    globalP = FALSE,
    globalPKeep = FALSE,
    addStars = FALSE,
    starsShowCi = FALSE,
    starsShowP = FALSE,
    starsShowSe = TRUE,
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    addQ = FALSE,
    qMethod = "BH",
    boldQ = FALSE,
    boldQThreshold = 0.05,
    path = "~/Desktop/Multivariable Logistic Regression.docx",
    export = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblRegLogistic requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in dep) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(modelTerms, "formula")) modelTerms <- jmvcore::decomposeFormula(modelTerms)

    options <- tblRegLogisticOptions$new(
        dep = dep,
        covs = covs,
        factors = factors,
        modelTerms = modelTerms,
        exponentiate = exponentiate,
        digitsCoef = digitsCoef,
        confInt = confInt,
        confLevel = confLevel,
        ciMerge = ciMerge,
        intercept = intercept,
        addRefRowEstimate = addRefRowEstimate,
        addN = addN,
        addNLocation = addNLocation,
        addNEvent = addNEvent,
        addNEventLocation = addNEventLocation,
        addVif = addVif,
        modelFit = modelFit,
        digitsPvalue = digitsPvalue,
        boldPvalue = boldPvalue,
        boldPvalueThreshold = boldPvalueThreshold,
        globalP = globalP,
        globalPKeep = globalPKeep,
        addStars = addStars,
        starsShowCi = starsShowCi,
        starsShowP = starsShowP,
        starsShowSe = starsShowSe,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        addQ = addQ,
        qMethod = qMethod,
        boldQ = boldQ,
        boldQThreshold = boldQThreshold,
        path = path,
        export = export)

    analysis <- tblRegLogisticClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

