
# This file is automatically generated, you probably don't want to edit this

tblSummaryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varsCont = NULL,
            varsCat = NULL,
            groupBy = NULL,
            missing = "ifany",
            missingText = "Unknown",
            percent = "column",
            statContGlobal = "mean_sd",
            statsContSpecific = NULL,
            statCatGlobal = "n_percent",
            statsCatSpecific = NULL,
            pValue = FALSE,
            testContGlobal = "auto",
            testsContSpecific = list(),
            testCatGlobal = "auto",
            testsCatSpecific = list(),
            export = FALSE,
            path = "~/Desktop/summary_table.docx", ...) {

            super$initialize(
                package="SummaryTables",
                name="tblSummary",
                requiresData=TRUE,
                ...)

            private$..varsCont <- jmvcore::OptionVariables$new(
                "varsCont",
                varsCont,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..varsCat <- jmvcore::OptionVariables$new(
                "varsCat",
                varsCat,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..groupBy <- jmvcore::OptionVariable$new(
                "groupBy",
                groupBy,
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "ifany",
                    "no",
                    "always"),
                default="ifany")
            private$..missingText <- jmvcore::OptionString$new(
                "missingText",
                missingText,
                default="Unknown")
            private$..percent <- jmvcore::OptionList$new(
                "percent",
                percent,
                options=list(
                    "column",
                    "row",
                    "cell"),
                default="column")
            private$..statContGlobal <- jmvcore::OptionList$new(
                "statContGlobal",
                statContGlobal,
                options=list(
                    "mean_sd",
                    "median_iqr",
                    "range"),
                default="mean_sd")
            private$..statsContSpecific <- jmvcore::OptionArray$new(
                "statsContSpecific",
                statsContSpecific,
                template=jmvcore::OptionGroup$new(
                    "statsContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "use_global",
                                "mean_sd",
                                "median_iqr",
                                "range"),
                            default="use_global"))))
            private$..statCatGlobal <- jmvcore::OptionList$new(
                "statCatGlobal",
                statCatGlobal,
                options=list(
                    "n_percent",
                    "n_total_percent"),
                default="n_percent")
            private$..statsCatSpecific <- jmvcore::OptionArray$new(
                "statsCatSpecific",
                statsCatSpecific,
                template=jmvcore::OptionGroup$new(
                    "statsCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "use_global",
                                "n_percent",
                                "n_total_percent"),
                            default="use_global"))))
            private$..pValue <- jmvcore::OptionBool$new(
                "pValue",
                pValue,
                default=FALSE)
            private$..testContGlobal <- jmvcore::OptionList$new(
                "testContGlobal",
                testContGlobal,
                options=list(
                    "auto",
                    "t.test",
                    "oneway.test",
                    "paired.t.test",
                    "wilcox.test",
                    "kruskal.test",
                    "paired.wilcox.test",
                    "mood.test",
                    "ancova",
                    "lme4"),
                default="auto")
            private$..testsContSpecific <- jmvcore::OptionArray$new(
                "testsContSpecific",
                testsContSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "testsContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "test",
                            NULL,
                            options=list(
                                "use_global",
                                "auto",
                                "t.test",
                                "oneway.test",
                                "paired.t.test",
                                "wilcox.test",
                                "kruskal.test",
                                "paired.wilcox.test",
                                "mood.test",
                                "ancova",
                                "lme4"),
                            default="use_global"))))
            private$..testCatGlobal <- jmvcore::OptionList$new(
                "testCatGlobal",
                testCatGlobal,
                options=list(
                    "auto",
                    "chisq.test.no.correct",
                    "chisq.test",
                    "fisher.test",
                    "mcnemar.test",
                    "mcnemar.test.wide",
                    "prop.test",
                    "lme4"),
                default="auto")
            private$..testsCatSpecific <- jmvcore::OptionArray$new(
                "testsCatSpecific",
                testsCatSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "testsCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "test",
                            NULL,
                            options=list(
                                "use_global",
                                "auto",
                                "chisq.test.no.correct",
                                "chisq.test",
                                "fisher.test",
                                "mcnemar.test",
                                "mcnemar.test.wide",
                                "prop.test",
                                "lme4"),
                            default="use_global"))))
            private$..export <- jmvcore::OptionBool$new(
                "export",
                export,
                default=FALSE)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/summary_table.docx")

            self$.addOption(private$..varsCont)
            self$.addOption(private$..varsCat)
            self$.addOption(private$..groupBy)
            self$.addOption(private$..missing)
            self$.addOption(private$..missingText)
            self$.addOption(private$..percent)
            self$.addOption(private$..statContGlobal)
            self$.addOption(private$..statsContSpecific)
            self$.addOption(private$..statCatGlobal)
            self$.addOption(private$..statsCatSpecific)
            self$.addOption(private$..pValue)
            self$.addOption(private$..testContGlobal)
            self$.addOption(private$..testsContSpecific)
            self$.addOption(private$..testCatGlobal)
            self$.addOption(private$..testsCatSpecific)
            self$.addOption(private$..export)
            self$.addOption(private$..path)
        }),
    active = list(
        varsCont = function() private$..varsCont$value,
        varsCat = function() private$..varsCat$value,
        groupBy = function() private$..groupBy$value,
        missing = function() private$..missing$value,
        missingText = function() private$..missingText$value,
        percent = function() private$..percent$value,
        statContGlobal = function() private$..statContGlobal$value,
        statsContSpecific = function() private$..statsContSpecific$value,
        statCatGlobal = function() private$..statCatGlobal$value,
        statsCatSpecific = function() private$..statsCatSpecific$value,
        pValue = function() private$..pValue$value,
        testContGlobal = function() private$..testContGlobal$value,
        testsContSpecific = function() private$..testsContSpecific$value,
        testCatGlobal = function() private$..testCatGlobal$value,
        testsCatSpecific = function() private$..testsCatSpecific$value,
        export = function() private$..export$value,
        path = function() private$..path$value),
    private = list(
        ..varsCont = NA,
        ..varsCat = NA,
        ..groupBy = NA,
        ..missing = NA,
        ..missingText = NA,
        ..percent = NA,
        ..statContGlobal = NA,
        ..statsContSpecific = NA,
        ..statCatGlobal = NA,
        ..statsCatSpecific = NA,
        ..pValue = NA,
        ..testContGlobal = NA,
        ..testsContSpecific = NA,
        ..testCatGlobal = NA,
        ..testsCatSpecific = NA,
        ..export = NA,
        ..path = NA)
)

tblSummaryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Table Summary")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                title="Table Summary"))}))

tblSummaryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblSummary",
                version = c(1,0,0),
                options = options,
                results = tblSummaryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Table Summary
#'
#' 
#' @param data .
#' @param varsCont .
#' @param varsCat .
#' @param groupBy .
#' @param missing .
#' @param missingText .
#' @param percent .
#' @param statContGlobal .
#' @param statsContSpecific .
#' @param statCatGlobal .
#' @param statsCatSpecific .
#' @param pValue .
#' @param testContGlobal .
#' @param testsContSpecific .
#' @param testCatGlobal .
#' @param testsCatSpecific .
#' @param export .
#' @param path .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblSummary <- function(
    data,
    varsCont,
    varsCat,
    groupBy,
    missing = "ifany",
    missingText = "Unknown",
    percent = "column",
    statContGlobal = "mean_sd",
    statsContSpecific,
    statCatGlobal = "n_percent",
    statsCatSpecific,
    pValue = FALSE,
    testContGlobal = "auto",
    testsContSpecific = list(),
    testCatGlobal = "auto",
    testsCatSpecific = list(),
    export = FALSE,
    path = "~/Desktop/summary_table.docx") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblSummary requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varsCont)) varsCont <- jmvcore::resolveQuo(jmvcore::enquo(varsCont))
    if ( ! missing(varsCat)) varsCat <- jmvcore::resolveQuo(jmvcore::enquo(varsCat))
    if ( ! missing(groupBy)) groupBy <- jmvcore::resolveQuo(jmvcore::enquo(groupBy))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varsCont), varsCont, NULL),
            `if`( ! missing(varsCat), varsCat, NULL),
            `if`( ! missing(groupBy), groupBy, NULL))


    options <- tblSummaryOptions$new(
        varsCont = varsCont,
        varsCat = varsCat,
        groupBy = groupBy,
        missing = missing,
        missingText = missingText,
        percent = percent,
        statContGlobal = statContGlobal,
        statsContSpecific = statsContSpecific,
        statCatGlobal = statCatGlobal,
        statsCatSpecific = statsCatSpecific,
        pValue = pValue,
        testContGlobal = testContGlobal,
        testsContSpecific = testsContSpecific,
        testCatGlobal = testCatGlobal,
        testsCatSpecific = testsCatSpecific,
        export = export,
        path = path)

    analysis <- tblSummaryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

