
# This file is automatically generated, you probably don't want to edit this

tblSummaryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            by = NULL,
            statistic = "auto",
            missing = "ifany",
            missingText = "Unknown",
            percent = "column",
            p_value = FALSE,
            exportWord = FALSE,
            exportPath = "~/Desktop/summary_table.docx", ...) {

            super$initialize(
                package="SummaryTables",
                name="tblSummary",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous",
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..by <- jmvcore::OptionVariable$new(
                "by",
                by,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"))
            private$..statistic <- jmvcore::OptionList$new(
                "statistic",
                statistic,
                options=list(
                    "auto",
                    "mean_sd",
                    "median_iqr",
                    "n_percent"),
                default="auto")
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "ifany",
                    "no",
                    "always"),
                default="ifany")
            private$..missingText <- jmvcore::OptionString$new(
                "missingText",
                missingText,
                default="Unknown")
            private$..percent <- jmvcore::OptionList$new(
                "percent",
                percent,
                options=list(
                    "column",
                    "row",
                    "cell"),
                default="column")
            private$..p_value <- jmvcore::OptionBool$new(
                "p_value",
                p_value,
                default=FALSE)
            private$..exportWord <- jmvcore::OptionBool$new(
                "exportWord",
                exportWord,
                default=FALSE)
            private$..exportPath <- jmvcore::OptionString$new(
                "exportPath",
                exportPath,
                default="~/Desktop/summary_table.docx")

            self$.addOption(private$..vars)
            self$.addOption(private$..by)
            self$.addOption(private$..statistic)
            self$.addOption(private$..missing)
            self$.addOption(private$..missingText)
            self$.addOption(private$..percent)
            self$.addOption(private$..p_value)
            self$.addOption(private$..exportWord)
            self$.addOption(private$..exportPath)
        }),
    active = list(
        vars = function() private$..vars$value,
        by = function() private$..by$value,
        statistic = function() private$..statistic$value,
        missing = function() private$..missing$value,
        missingText = function() private$..missingText$value,
        percent = function() private$..percent$value,
        p_value = function() private$..p_value$value,
        exportWord = function() private$..exportWord$value,
        exportPath = function() private$..exportPath$value),
    private = list(
        ..vars = NA,
        ..by = NA,
        ..statistic = NA,
        ..missing = NA,
        ..missingText = NA,
        ..percent = NA,
        ..p_value = NA,
        ..exportWord = NA,
        ..exportPath = NA)
)

tblSummaryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Table Summary")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                title="Table Summary"))}))

tblSummaryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblSummary",
                version = c(1,0,0),
                options = options,
                results = tblSummaryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Table Summary
#'
#' 
#' @param data .
#' @param vars .
#' @param by .
#' @param statistic .
#' @param missing .
#' @param missingText .
#' @param percent .
#' @param p_value .
#' @param exportWord .
#' @param exportPath .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblSummary <- function(
    data,
    vars,
    by,
    statistic = "auto",
    missing = "ifany",
    missingText = "Unknown",
    percent = "column",
    p_value = FALSE,
    exportWord = FALSE,
    exportPath = "~/Desktop/summary_table.docx") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblSummary requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(by)) by <- jmvcore::resolveQuo(jmvcore::enquo(by))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(by), by, NULL))


    options <- tblSummaryOptions$new(
        vars = vars,
        by = by,
        statistic = statistic,
        missing = missing,
        missingText = missingText,
        percent = percent,
        p_value = p_value,
        exportWord = exportWord,
        exportPath = exportPath)

    analysis <- tblSummaryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

