
# This file is automatically generated, you probably don't want to edit this

tblSurvfitOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSurvfitOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsed = NULL,
            event = NULL,
            eventLevel = NULL,
            strata = NULL,
            statistic = "times",
            times = "12, 24",
            type = "survival",
            probs = "50",
            digitsEstimate = "auto",
            confLevel = 95,
            addN = FALSE,
            addNEvent = FALSE,
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            path = "~/Desktop/Survival Table.docx",
            export = FALSE, ...) {

            super$initialize(
                package="SummaryTables",
                name="tblSurvfit",
                requiresData=TRUE,
                ...)

            private$..elapsed <- jmvcore::OptionVariable$new(
                "elapsed",
                elapsed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..strata <- jmvcore::OptionVariables$new(
                "strata",
                strata,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..statistic <- jmvcore::OptionList$new(
                "statistic",
                statistic,
                options=list(
                    "times",
                    "probs"),
                default="times")
            private$..times <- jmvcore::OptionString$new(
                "times",
                times,
                default="12, 24")
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "survival",
                    "risk",
                    "cumhaz"),
                default="survival")
            private$..probs <- jmvcore::OptionString$new(
                "probs",
                probs,
                default="50")
            private$..digitsEstimate <- jmvcore::OptionList$new(
                "digitsEstimate",
                digitsEstimate,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=50,
                max=99.9,
                default=95)
            private$..addN <- jmvcore::OptionBool$new(
                "addN",
                addN,
                default=FALSE)
            private$..addNEvent <- jmvcore::OptionBool$new(
                "addNEvent",
                addNEvent,
                default=FALSE)
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/Survival Table.docx")
            private$..export <- jmvcore::OptionAction$new(
                "export",
                export)

            self$.addOption(private$..elapsed)
            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..strata)
            self$.addOption(private$..statistic)
            self$.addOption(private$..times)
            self$.addOption(private$..type)
            self$.addOption(private$..probs)
            self$.addOption(private$..digitsEstimate)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..addN)
            self$.addOption(private$..addNEvent)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..path)
            self$.addOption(private$..export)
        }),
    active = list(
        elapsed = function() private$..elapsed$value,
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        strata = function() private$..strata$value,
        statistic = function() private$..statistic$value,
        times = function() private$..times$value,
        type = function() private$..type$value,
        probs = function() private$..probs$value,
        digitsEstimate = function() private$..digitsEstimate$value,
        confLevel = function() private$..confLevel$value,
        addN = function() private$..addN$value,
        addNEvent = function() private$..addNEvent$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        path = function() private$..path$value,
        export = function() private$..export$value),
    private = list(
        ..elapsed = NA,
        ..event = NA,
        ..eventLevel = NA,
        ..strata = NA,
        ..statistic = NA,
        ..times = NA,
        ..type = NA,
        ..probs = NA,
        ..digitsEstimate = NA,
        ..confLevel = NA,
        ..addN = NA,
        ..addNEvent = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..path = NA,
        ..export = NA)
)

tblSurvfitResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSurvfitResults",
    inherit = jmvcore::Group,
    active = list(
        status = function() private$.items[["status"]],
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Survival Table")
            self$add(jmvcore::Table$new(
                options=options,
                name="status",
                title="Generating Table\u2026",
                columns=list()))
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                refs=list(
                    "SummaryTables",
                    "gtsummary")))}))

tblSurvfitBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSurvfitBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblSurvfit",
                version = c(1,0,0),
                options = options,
                results = tblSurvfitResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Survival Table
#'
#' 
#' @param data .
#' @param elapsed .
#' @param event .
#' @param eventLevel .
#' @param strata .
#' @param statistic .
#' @param times .
#' @param type .
#' @param probs .
#' @param digitsEstimate .
#' @param confLevel .
#' @param addN .
#' @param addNEvent .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param path .
#' @param export .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$status} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$status$asDF}
#'
#' \code{as.data.frame(results$status)}
#'
#' @export
tblSurvfit <- function(
    data,
    elapsed,
    event,
    eventLevel,
    strata,
    statistic = "times",
    times = "12, 24",
    type = "survival",
    probs = "50",
    digitsEstimate = "auto",
    confLevel = 95,
    addN = FALSE,
    addNEvent = FALSE,
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    path = "~/Desktop/Survival Table.docx",
    export = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblSurvfit requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsed)) elapsed <- jmvcore::resolveQuo(jmvcore::enquo(elapsed))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsed), elapsed, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(strata), strata, NULL))

    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- tblSurvfitOptions$new(
        elapsed = elapsed,
        event = event,
        eventLevel = eventLevel,
        strata = strata,
        statistic = statistic,
        times = times,
        type = type,
        probs = probs,
        digitsEstimate = digitsEstimate,
        confLevel = confLevel,
        addN = addN,
        addNEvent = addNEvent,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        path = path,
        export = export)

    analysis <- tblSurvfitClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

