
# This file is automatically generated, you probably don't want to edit this

tblSummaryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varsCont = NULL,
            varsCat = NULL,
            groupVar = NULL,
            addN = FALSE,
            addNLast = FALSE,
            addNFootnote = TRUE,
            addOverall = FALSE,
            addOverallLast = FALSE,
            missing = "ifany",
            missingText = "Unknown",
            missingStat = "n",
            journal = "default",
            compact = FALSE,
            language = "en",
            boldLabels = FALSE,
            boldLevels = FALSE,
            italicizeLabels = FALSE,
            italicizeLevels = FALSE,
            sortCatDefault = "alphanumeric",
            sortCatSpecific = NULL,
            statContDefault = "meanSd",
            statContSpecific = NULL,
            digitsCont = "auto",
            statCatDefault = "nPercent",
            statCatSpecific = NULL,
            digitsCatPct = "auto",
            percent = "column",
            addDifference = FALSE,
            diffConfLevel = 95,
            diffDigitsPvalue = "auto",
            boldDiffPvalue = FALSE,
            boldDiffPvalueThreshold = 0.05,
            separateDiffPFootnotes = FALSE,
            diffContDefault = "t.test",
            diffContSpecific = list(),
            diffDigitsCont = "auto",
            diffDichotDefault = "prop.test",
            diffDichotSpecific = list(),
            diffDigitsDichot = "auto",
            diffDigitsCat = "auto",
            addPvalue = FALSE,
            digitsPvalue = "auto",
            boldPvalue = FALSE,
            boldPvalueThreshold = 0.05,
            separatePvalueFootnotes = FALSE,
            testContDefault = "parametric",
            testContSpecific = list(),
            testCatDefault = "auto",
            testCatSpecific = list(),
            addQ = FALSE,
            qMethod = "BH",
            boldQ = FALSE,
            boldQThreshold = 0.05,
            addCi = FALSE,
            confLevel = 95,
            ciCombine = FALSE,
            ciContDefault = "t.test",
            ciContSpecific = list(),
            ciDigitsCont = "auto",
            ciCatDefault = "wilson",
            ciCatSpecific = list(),
            ciDigitsCat = "auto",
            export = FALSE,
            path = "~/Desktop/Summary Table.docx", ...) {

            super$initialize(
                package="SummaryTables",
                name="tblSummary",
                requiresData=TRUE,
                ...)

            private$..varsCont <- jmvcore::OptionVariables$new(
                "varsCont",
                varsCont,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..varsCat <- jmvcore::OptionVariables$new(
                "varsCat",
                varsCat,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..groupVar <- jmvcore::OptionVariable$new(
                "groupVar",
                groupVar,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..addN <- jmvcore::OptionBool$new(
                "addN",
                addN,
                default=FALSE)
            private$..addNLast <- jmvcore::OptionBool$new(
                "addNLast",
                addNLast,
                default=FALSE)
            private$..addNFootnote <- jmvcore::OptionBool$new(
                "addNFootnote",
                addNFootnote,
                default=TRUE)
            private$..addOverall <- jmvcore::OptionBool$new(
                "addOverall",
                addOverall,
                default=FALSE)
            private$..addOverallLast <- jmvcore::OptionBool$new(
                "addOverallLast",
                addOverallLast,
                default=FALSE)
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "ifany",
                    "no",
                    "always"),
                default="ifany")
            private$..missingText <- jmvcore::OptionString$new(
                "missingText",
                missingText,
                default="Unknown")
            private$..missingStat <- jmvcore::OptionList$new(
                "missingStat",
                missingStat,
                options=list(
                    "n",
                    "nPercent",
                    "percent"),
                default="n")
            private$..journal <- jmvcore::OptionList$new(
                "journal",
                journal,
                options=list(
                    "default",
                    "jama",
                    "lancet",
                    "nejm",
                    "qjecon"),
                default="default")
            private$..compact <- jmvcore::OptionBool$new(
                "compact",
                compact,
                default=FALSE)
            private$..language <- jmvcore::OptionList$new(
                "language",
                language,
                options=list(
                    "zh-cn",
                    "zh-tw",
                    "nl",
                    "en",
                    "fr",
                    "de",
                    "gu",
                    "hi",
                    "is",
                    "ja",
                    "kr",
                    "mr",
                    "no",
                    "pt",
                    "es",
                    "se"),
                default="en")
            private$..boldLabels <- jmvcore::OptionBool$new(
                "boldLabels",
                boldLabels,
                default=FALSE)
            private$..boldLevels <- jmvcore::OptionBool$new(
                "boldLevels",
                boldLevels,
                default=FALSE)
            private$..italicizeLabels <- jmvcore::OptionBool$new(
                "italicizeLabels",
                italicizeLabels,
                default=FALSE)
            private$..italicizeLevels <- jmvcore::OptionBool$new(
                "italicizeLevels",
                italicizeLevels,
                default=FALSE)
            private$..sortCatDefault <- jmvcore::OptionList$new(
                "sortCatDefault",
                sortCatDefault,
                options=list(
                    "alphanumeric",
                    "frequency"),
                default="alphanumeric")
            private$..sortCatSpecific <- jmvcore::OptionArray$new(
                "sortCatSpecific",
                sortCatSpecific,
                template=jmvcore::OptionGroup$new(
                    "sortCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "sort",
                            NULL,
                            options=list(
                                "useDefault",
                                "alphanumeric",
                                "frequency"),
                            default="useDefault"))))
            private$..statContDefault <- jmvcore::OptionList$new(
                "statContDefault",
                statContDefault,
                options=list(
                    "meanSd",
                    "medianIqr",
                    "medianRange",
                    "mean",
                    "median",
                    "eda"),
                default="meanSd")
            private$..statContSpecific <- jmvcore::OptionArray$new(
                "statContSpecific",
                statContSpecific,
                template=jmvcore::OptionGroup$new(
                    "statContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "useDefault",
                                "meanSd",
                                "medianIqr",
                                "medianRange",
                                "mean",
                                "median",
                                "eda"),
                            default="useDefault"))))
            private$..digitsCont <- jmvcore::OptionList$new(
                "digitsCont",
                digitsCont,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..statCatDefault <- jmvcore::OptionList$new(
                "statCatDefault",
                statCatDefault,
                options=list(
                    "nPercent",
                    "n",
                    "percent"),
                default="nPercent")
            private$..statCatSpecific <- jmvcore::OptionArray$new(
                "statCatSpecific",
                statCatSpecific,
                template=jmvcore::OptionGroup$new(
                    "statCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "stat",
                            NULL,
                            options=list(
                                "useDefault",
                                "nPercent",
                                "n",
                                "percent"),
                            default="useDefault"))))
            private$..digitsCatPct <- jmvcore::OptionList$new(
                "digitsCatPct",
                digitsCatPct,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..percent <- jmvcore::OptionList$new(
                "percent",
                percent,
                options=list(
                    "column",
                    "row",
                    "cell"),
                default="column")
            private$..addDifference <- jmvcore::OptionBool$new(
                "addDifference",
                addDifference,
                default=FALSE)
            private$..diffConfLevel <- jmvcore::OptionNumber$new(
                "diffConfLevel",
                diffConfLevel,
                min=50,
                max=99.9,
                default=95)
            private$..diffDigitsPvalue <- jmvcore::OptionList$new(
                "diffDigitsPvalue",
                diffDigitsPvalue,
                options=list(
                    "auto",
                    "1",
                    "2",
                    "3"),
                default="auto")
            private$..boldDiffPvalue <- jmvcore::OptionBool$new(
                "boldDiffPvalue",
                boldDiffPvalue,
                default=FALSE)
            private$..boldDiffPvalueThreshold <- jmvcore::OptionNumber$new(
                "boldDiffPvalueThreshold",
                boldDiffPvalueThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..separateDiffPFootnotes <- jmvcore::OptionBool$new(
                "separateDiffPFootnotes",
                separateDiffPFootnotes,
                default=FALSE)
            private$..diffContDefault <- jmvcore::OptionList$new(
                "diffContDefault",
                diffContDefault,
                options=list(
                    "t.test",
                    "t.test.equalVar",
                    "wilcox.test",
                    "cohens_d",
                    "hedges_g",
                    "smd"),
                default="t.test")
            private$..diffContSpecific <- jmvcore::OptionArray$new(
                "diffContSpecific",
                diffContSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "diffContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "method",
                            NULL,
                            options=list(
                                "useDefault",
                                "t.test",
                                "t.test.equalVar",
                                "wilcox.test",
                                "cohens_d",
                                "hedges_g",
                                "smd"),
                            default="useDefault"))))
            private$..diffDigitsCont <- jmvcore::OptionList$new(
                "diffDigitsCont",
                diffDigitsCont,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..diffDichotDefault <- jmvcore::OptionList$new(
                "diffDichotDefault",
                diffDichotDefault,
                options=list(
                    "prop.test",
                    "smd"),
                default="prop.test")
            private$..diffDichotSpecific <- jmvcore::OptionArray$new(
                "diffDichotSpecific",
                diffDichotSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "diffDichotSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "method",
                            NULL,
                            options=list(
                                "useDefault",
                                "prop.test",
                                "smd"),
                            default="useDefault"))))
            private$..diffDigitsDichot <- jmvcore::OptionList$new(
                "diffDigitsDichot",
                diffDigitsDichot,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..diffDigitsCat <- jmvcore::OptionList$new(
                "diffDigitsCat",
                diffDigitsCat,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..addPvalue <- jmvcore::OptionBool$new(
                "addPvalue",
                addPvalue,
                default=FALSE)
            private$..digitsPvalue <- jmvcore::OptionList$new(
                "digitsPvalue",
                digitsPvalue,
                options=list(
                    "auto",
                    "1",
                    "2",
                    "3"),
                default="auto")
            private$..boldPvalue <- jmvcore::OptionBool$new(
                "boldPvalue",
                boldPvalue,
                default=FALSE)
            private$..boldPvalueThreshold <- jmvcore::OptionNumber$new(
                "boldPvalueThreshold",
                boldPvalueThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..separatePvalueFootnotes <- jmvcore::OptionBool$new(
                "separatePvalueFootnotes",
                separatePvalueFootnotes,
                default=FALSE)
            private$..testContDefault <- jmvcore::OptionList$new(
                "testContDefault",
                testContDefault,
                options=list(
                    "parametric",
                    "nonparametric",
                    "t.test",
                    "t.test.equalVar",
                    "oneway.test",
                    "oneway.test.equalVar",
                    "wilcox.test",
                    "kruskal.test"),
                default="parametric")
            private$..testContSpecific <- jmvcore::OptionArray$new(
                "testContSpecific",
                testContSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "testContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "test",
                            NULL,
                            options=list(
                                "useDefault",
                                "t.test",
                                "t.test.equalVar",
                                "oneway.test",
                                "oneway.test.equalVar",
                                "wilcox.test",
                                "kruskal.test"),
                            default="useDefault"))))
            private$..testCatDefault <- jmvcore::OptionList$new(
                "testCatDefault",
                testCatDefault,
                options=list(
                    "auto",
                    "chisq.test.no.correct",
                    "chisq.test",
                    "fisher.test"),
                default="auto")
            private$..testCatSpecific <- jmvcore::OptionArray$new(
                "testCatSpecific",
                testCatSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "testCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "test",
                            NULL,
                            options=list(
                                "useDefault",
                                "chisq.test.no.correct",
                                "chisq.test",
                                "fisher.test"),
                            default="useDefault"))))
            private$..addQ <- jmvcore::OptionBool$new(
                "addQ",
                addQ,
                default=FALSE)
            private$..qMethod <- jmvcore::OptionList$new(
                "qMethod",
                qMethod,
                options=list(
                    "BH",
                    "BY",
                    "bonferroni",
                    "holm",
                    "hochberg",
                    "hommel",
                    "none"),
                default="BH")
            private$..boldQ <- jmvcore::OptionBool$new(
                "boldQ",
                boldQ,
                default=FALSE)
            private$..boldQThreshold <- jmvcore::OptionNumber$new(
                "boldQThreshold",
                boldQThreshold,
                min=0,
                max=1,
                default=0.05)
            private$..addCi <- jmvcore::OptionBool$new(
                "addCi",
                addCi,
                default=FALSE)
            private$..confLevel <- jmvcore::OptionNumber$new(
                "confLevel",
                confLevel,
                min=50,
                max=99.9,
                default=95)
            private$..ciCombine <- jmvcore::OptionBool$new(
                "ciCombine",
                ciCombine,
                default=FALSE)
            private$..ciContDefault <- jmvcore::OptionList$new(
                "ciContDefault",
                ciContDefault,
                options=list(
                    "t.test",
                    "wilcox.test"),
                default="t.test")
            private$..ciContSpecific <- jmvcore::OptionArray$new(
                "ciContSpecific",
                ciContSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "ciContSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "method",
                            NULL,
                            options=list(
                                "useDefault",
                                "t.test",
                                "wilcox.test"),
                            default="useDefault"))))
            private$..ciDigitsCont <- jmvcore::OptionList$new(
                "ciDigitsCont",
                ciDigitsCont,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..ciCatDefault <- jmvcore::OptionList$new(
                "ciCatDefault",
                ciCatDefault,
                options=list(
                    "wilson",
                    "wilson.no.correct",
                    "exact",
                    "wald",
                    "wald.no.correct",
                    "agresti.coull",
                    "jeffreys"),
                default="wilson")
            private$..ciCatSpecific <- jmvcore::OptionArray$new(
                "ciCatSpecific",
                ciCatSpecific,
                default=list(),
                template=jmvcore::OptionGroup$new(
                    "ciCatSpecific",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL),
                        jmvcore::OptionList$new(
                            "method",
                            NULL,
                            options=list(
                                "useDefault",
                                "wilson",
                                "wilson.no.correct",
                                "exact",
                                "wald",
                                "wald.no.correct",
                                "agresti.coull",
                                "jeffreys"),
                            default="useDefault"))))
            private$..ciDigitsCat <- jmvcore::OptionList$new(
                "ciDigitsCat",
                ciDigitsCat,
                options=list(
                    "auto",
                    "0",
                    "1",
                    "2",
                    "3",
                    "4",
                    "5"),
                default="auto")
            private$..export <- jmvcore::OptionBool$new(
                "export",
                export,
                default=FALSE)
            private$..path <- jmvcore::OptionString$new(
                "path",
                path,
                default="~/Desktop/Summary Table.docx")

            self$.addOption(private$..varsCont)
            self$.addOption(private$..varsCat)
            self$.addOption(private$..groupVar)
            self$.addOption(private$..addN)
            self$.addOption(private$..addNLast)
            self$.addOption(private$..addNFootnote)
            self$.addOption(private$..addOverall)
            self$.addOption(private$..addOverallLast)
            self$.addOption(private$..missing)
            self$.addOption(private$..missingText)
            self$.addOption(private$..missingStat)
            self$.addOption(private$..journal)
            self$.addOption(private$..compact)
            self$.addOption(private$..language)
            self$.addOption(private$..boldLabels)
            self$.addOption(private$..boldLevels)
            self$.addOption(private$..italicizeLabels)
            self$.addOption(private$..italicizeLevels)
            self$.addOption(private$..sortCatDefault)
            self$.addOption(private$..sortCatSpecific)
            self$.addOption(private$..statContDefault)
            self$.addOption(private$..statContSpecific)
            self$.addOption(private$..digitsCont)
            self$.addOption(private$..statCatDefault)
            self$.addOption(private$..statCatSpecific)
            self$.addOption(private$..digitsCatPct)
            self$.addOption(private$..percent)
            self$.addOption(private$..addDifference)
            self$.addOption(private$..diffConfLevel)
            self$.addOption(private$..diffDigitsPvalue)
            self$.addOption(private$..boldDiffPvalue)
            self$.addOption(private$..boldDiffPvalueThreshold)
            self$.addOption(private$..separateDiffPFootnotes)
            self$.addOption(private$..diffContDefault)
            self$.addOption(private$..diffContSpecific)
            self$.addOption(private$..diffDigitsCont)
            self$.addOption(private$..diffDichotDefault)
            self$.addOption(private$..diffDichotSpecific)
            self$.addOption(private$..diffDigitsDichot)
            self$.addOption(private$..diffDigitsCat)
            self$.addOption(private$..addPvalue)
            self$.addOption(private$..digitsPvalue)
            self$.addOption(private$..boldPvalue)
            self$.addOption(private$..boldPvalueThreshold)
            self$.addOption(private$..separatePvalueFootnotes)
            self$.addOption(private$..testContDefault)
            self$.addOption(private$..testContSpecific)
            self$.addOption(private$..testCatDefault)
            self$.addOption(private$..testCatSpecific)
            self$.addOption(private$..addQ)
            self$.addOption(private$..qMethod)
            self$.addOption(private$..boldQ)
            self$.addOption(private$..boldQThreshold)
            self$.addOption(private$..addCi)
            self$.addOption(private$..confLevel)
            self$.addOption(private$..ciCombine)
            self$.addOption(private$..ciContDefault)
            self$.addOption(private$..ciContSpecific)
            self$.addOption(private$..ciDigitsCont)
            self$.addOption(private$..ciCatDefault)
            self$.addOption(private$..ciCatSpecific)
            self$.addOption(private$..ciDigitsCat)
            self$.addOption(private$..export)
            self$.addOption(private$..path)
        }),
    active = list(
        varsCont = function() private$..varsCont$value,
        varsCat = function() private$..varsCat$value,
        groupVar = function() private$..groupVar$value,
        addN = function() private$..addN$value,
        addNLast = function() private$..addNLast$value,
        addNFootnote = function() private$..addNFootnote$value,
        addOverall = function() private$..addOverall$value,
        addOverallLast = function() private$..addOverallLast$value,
        missing = function() private$..missing$value,
        missingText = function() private$..missingText$value,
        missingStat = function() private$..missingStat$value,
        journal = function() private$..journal$value,
        compact = function() private$..compact$value,
        language = function() private$..language$value,
        boldLabels = function() private$..boldLabels$value,
        boldLevels = function() private$..boldLevels$value,
        italicizeLabels = function() private$..italicizeLabels$value,
        italicizeLevels = function() private$..italicizeLevels$value,
        sortCatDefault = function() private$..sortCatDefault$value,
        sortCatSpecific = function() private$..sortCatSpecific$value,
        statContDefault = function() private$..statContDefault$value,
        statContSpecific = function() private$..statContSpecific$value,
        digitsCont = function() private$..digitsCont$value,
        statCatDefault = function() private$..statCatDefault$value,
        statCatSpecific = function() private$..statCatSpecific$value,
        digitsCatPct = function() private$..digitsCatPct$value,
        percent = function() private$..percent$value,
        addDifference = function() private$..addDifference$value,
        diffConfLevel = function() private$..diffConfLevel$value,
        diffDigitsPvalue = function() private$..diffDigitsPvalue$value,
        boldDiffPvalue = function() private$..boldDiffPvalue$value,
        boldDiffPvalueThreshold = function() private$..boldDiffPvalueThreshold$value,
        separateDiffPFootnotes = function() private$..separateDiffPFootnotes$value,
        diffContDefault = function() private$..diffContDefault$value,
        diffContSpecific = function() private$..diffContSpecific$value,
        diffDigitsCont = function() private$..diffDigitsCont$value,
        diffDichotDefault = function() private$..diffDichotDefault$value,
        diffDichotSpecific = function() private$..diffDichotSpecific$value,
        diffDigitsDichot = function() private$..diffDigitsDichot$value,
        diffDigitsCat = function() private$..diffDigitsCat$value,
        addPvalue = function() private$..addPvalue$value,
        digitsPvalue = function() private$..digitsPvalue$value,
        boldPvalue = function() private$..boldPvalue$value,
        boldPvalueThreshold = function() private$..boldPvalueThreshold$value,
        separatePvalueFootnotes = function() private$..separatePvalueFootnotes$value,
        testContDefault = function() private$..testContDefault$value,
        testContSpecific = function() private$..testContSpecific$value,
        testCatDefault = function() private$..testCatDefault$value,
        testCatSpecific = function() private$..testCatSpecific$value,
        addQ = function() private$..addQ$value,
        qMethod = function() private$..qMethod$value,
        boldQ = function() private$..boldQ$value,
        boldQThreshold = function() private$..boldQThreshold$value,
        addCi = function() private$..addCi$value,
        confLevel = function() private$..confLevel$value,
        ciCombine = function() private$..ciCombine$value,
        ciContDefault = function() private$..ciContDefault$value,
        ciContSpecific = function() private$..ciContSpecific$value,
        ciDigitsCont = function() private$..ciDigitsCont$value,
        ciCatDefault = function() private$..ciCatDefault$value,
        ciCatSpecific = function() private$..ciCatSpecific$value,
        ciDigitsCat = function() private$..ciDigitsCat$value,
        export = function() private$..export$value,
        path = function() private$..path$value),
    private = list(
        ..varsCont = NA,
        ..varsCat = NA,
        ..groupVar = NA,
        ..addN = NA,
        ..addNLast = NA,
        ..addNFootnote = NA,
        ..addOverall = NA,
        ..addOverallLast = NA,
        ..missing = NA,
        ..missingText = NA,
        ..missingStat = NA,
        ..journal = NA,
        ..compact = NA,
        ..language = NA,
        ..boldLabels = NA,
        ..boldLevels = NA,
        ..italicizeLabels = NA,
        ..italicizeLevels = NA,
        ..sortCatDefault = NA,
        ..sortCatSpecific = NA,
        ..statContDefault = NA,
        ..statContSpecific = NA,
        ..digitsCont = NA,
        ..statCatDefault = NA,
        ..statCatSpecific = NA,
        ..digitsCatPct = NA,
        ..percent = NA,
        ..addDifference = NA,
        ..diffConfLevel = NA,
        ..diffDigitsPvalue = NA,
        ..boldDiffPvalue = NA,
        ..boldDiffPvalueThreshold = NA,
        ..separateDiffPFootnotes = NA,
        ..diffContDefault = NA,
        ..diffContSpecific = NA,
        ..diffDigitsCont = NA,
        ..diffDichotDefault = NA,
        ..diffDichotSpecific = NA,
        ..diffDigitsDichot = NA,
        ..diffDigitsCat = NA,
        ..addPvalue = NA,
        ..digitsPvalue = NA,
        ..boldPvalue = NA,
        ..boldPvalueThreshold = NA,
        ..separatePvalueFootnotes = NA,
        ..testContDefault = NA,
        ..testContSpecific = NA,
        ..testCatDefault = NA,
        ..testCatSpecific = NA,
        ..addQ = NA,
        ..qMethod = NA,
        ..boldQ = NA,
        ..boldQThreshold = NA,
        ..addCi = NA,
        ..confLevel = NA,
        ..ciCombine = NA,
        ..ciContDefault = NA,
        ..ciContSpecific = NA,
        ..ciDigitsCont = NA,
        ..ciCatDefault = NA,
        ..ciCatSpecific = NA,
        ..ciDigitsCat = NA,
        ..export = NA,
        ..path = NA)
)

tblSummaryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryResults",
    inherit = jmvcore::Group,
    active = list(
        tbl = function() private$.items[["tbl"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Table Summary")
            self$add(jmvcore::Html$new(
                options=options,
                name="tbl",
                title="Table Summary",
                clearWith=list()))}))

tblSummaryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "tblSummaryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SummaryTables",
                name = "tblSummary",
                version = c(1,0,0),
                options = options,
                results = tblSummaryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Summary Table
#'
#' 
#' @param data .
#' @param varsCont .
#' @param varsCat .
#' @param groupVar .
#' @param addN .
#' @param addNLast .
#' @param addNFootnote .
#' @param addOverall .
#' @param addOverallLast .
#' @param missing .
#' @param missingText .
#' @param missingStat .
#' @param journal .
#' @param compact .
#' @param language .
#' @param boldLabels .
#' @param boldLevels .
#' @param italicizeLabels .
#' @param italicizeLevels .
#' @param sortCatDefault .
#' @param sortCatSpecific .
#' @param statContDefault .
#' @param statContSpecific .
#' @param digitsCont .
#' @param statCatDefault .
#' @param statCatSpecific .
#' @param digitsCatPct .
#' @param percent .
#' @param addDifference .
#' @param diffConfLevel .
#' @param diffDigitsPvalue .
#' @param boldDiffPvalue .
#' @param boldDiffPvalueThreshold .
#' @param separateDiffPFootnotes .
#' @param diffContDefault .
#' @param diffContSpecific .
#' @param diffDigitsCont .
#' @param diffDichotDefault .
#' @param diffDichotSpecific .
#' @param diffDigitsDichot .
#' @param diffDigitsCat .
#' @param addPvalue .
#' @param digitsPvalue .
#' @param boldPvalue .
#' @param boldPvalueThreshold .
#' @param separatePvalueFootnotes .
#' @param testContDefault .
#' @param testContSpecific .
#' @param testCatDefault .
#' @param testCatSpecific .
#' @param addQ .
#' @param qMethod .
#' @param boldQ .
#' @param boldQThreshold .
#' @param addCi .
#' @param confLevel .
#' @param ciCombine .
#' @param ciContDefault .
#' @param ciContSpecific .
#' @param ciDigitsCont .
#' @param ciCatDefault .
#' @param ciCatSpecific .
#' @param ciDigitsCat .
#' @param export .
#' @param path .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$tbl} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tblSummary <- function(
    data,
    varsCont,
    varsCat,
    groupVar,
    addN = FALSE,
    addNLast = FALSE,
    addNFootnote = TRUE,
    addOverall = FALSE,
    addOverallLast = FALSE,
    missing = "ifany",
    missingText = "Unknown",
    missingStat = "n",
    journal = "default",
    compact = FALSE,
    language = "en",
    boldLabels = FALSE,
    boldLevels = FALSE,
    italicizeLabels = FALSE,
    italicizeLevels = FALSE,
    sortCatDefault = "alphanumeric",
    sortCatSpecific,
    statContDefault = "meanSd",
    statContSpecific,
    digitsCont = "auto",
    statCatDefault = "nPercent",
    statCatSpecific,
    digitsCatPct = "auto",
    percent = "column",
    addDifference = FALSE,
    diffConfLevel = 95,
    diffDigitsPvalue = "auto",
    boldDiffPvalue = FALSE,
    boldDiffPvalueThreshold = 0.05,
    separateDiffPFootnotes = FALSE,
    diffContDefault = "t.test",
    diffContSpecific = list(),
    diffDigitsCont = "auto",
    diffDichotDefault = "prop.test",
    diffDichotSpecific = list(),
    diffDigitsDichot = "auto",
    diffDigitsCat = "auto",
    addPvalue = FALSE,
    digitsPvalue = "auto",
    boldPvalue = FALSE,
    boldPvalueThreshold = 0.05,
    separatePvalueFootnotes = FALSE,
    testContDefault = "parametric",
    testContSpecific = list(),
    testCatDefault = "auto",
    testCatSpecific = list(),
    addQ = FALSE,
    qMethod = "BH",
    boldQ = FALSE,
    boldQThreshold = 0.05,
    addCi = FALSE,
    confLevel = 95,
    ciCombine = FALSE,
    ciContDefault = "t.test",
    ciContSpecific = list(),
    ciDigitsCont = "auto",
    ciCatDefault = "wilson",
    ciCatSpecific = list(),
    ciDigitsCat = "auto",
    export = FALSE,
    path = "~/Desktop/Summary Table.docx") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("tblSummary requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varsCont)) varsCont <- jmvcore::resolveQuo(jmvcore::enquo(varsCont))
    if ( ! missing(varsCat)) varsCat <- jmvcore::resolveQuo(jmvcore::enquo(varsCat))
    if ( ! missing(groupVar)) groupVar <- jmvcore::resolveQuo(jmvcore::enquo(groupVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varsCont), varsCont, NULL),
            `if`( ! missing(varsCat), varsCat, NULL),
            `if`( ! missing(groupVar), groupVar, NULL))


    options <- tblSummaryOptions$new(
        varsCont = varsCont,
        varsCat = varsCat,
        groupVar = groupVar,
        addN = addN,
        addNLast = addNLast,
        addNFootnote = addNFootnote,
        addOverall = addOverall,
        addOverallLast = addOverallLast,
        missing = missing,
        missingText = missingText,
        missingStat = missingStat,
        journal = journal,
        compact = compact,
        language = language,
        boldLabels = boldLabels,
        boldLevels = boldLevels,
        italicizeLabels = italicizeLabels,
        italicizeLevels = italicizeLevels,
        sortCatDefault = sortCatDefault,
        sortCatSpecific = sortCatSpecific,
        statContDefault = statContDefault,
        statContSpecific = statContSpecific,
        digitsCont = digitsCont,
        statCatDefault = statCatDefault,
        statCatSpecific = statCatSpecific,
        digitsCatPct = digitsCatPct,
        percent = percent,
        addDifference = addDifference,
        diffConfLevel = diffConfLevel,
        diffDigitsPvalue = diffDigitsPvalue,
        boldDiffPvalue = boldDiffPvalue,
        boldDiffPvalueThreshold = boldDiffPvalueThreshold,
        separateDiffPFootnotes = separateDiffPFootnotes,
        diffContDefault = diffContDefault,
        diffContSpecific = diffContSpecific,
        diffDigitsCont = diffDigitsCont,
        diffDichotDefault = diffDichotDefault,
        diffDichotSpecific = diffDichotSpecific,
        diffDigitsDichot = diffDigitsDichot,
        diffDigitsCat = diffDigitsCat,
        addPvalue = addPvalue,
        digitsPvalue = digitsPvalue,
        boldPvalue = boldPvalue,
        boldPvalueThreshold = boldPvalueThreshold,
        separatePvalueFootnotes = separatePvalueFootnotes,
        testContDefault = testContDefault,
        testContSpecific = testContSpecific,
        testCatDefault = testCatDefault,
        testCatSpecific = testCatSpecific,
        addQ = addQ,
        qMethod = qMethod,
        boldQ = boldQ,
        boldQThreshold = boldQThreshold,
        addCi = addCi,
        confLevel = confLevel,
        ciCombine = ciCombine,
        ciContDefault = ciContDefault,
        ciContSpecific = ciContSpecific,
        ciDigitsCont = ciDigitsCont,
        ciCatDefault = ciCatDefault,
        ciCatSpecific = ciCatSpecific,
        ciDigitsCat = ciDigitsCat,
        export = export,
        path = path)

    analysis <- tblSummaryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

